import os


# Имя выходного файла
OUTPUT_FILE = 'project_context.txt'

# Папки, которые нужно игнорировать
IGNORE_DIRS = {
    'venv', '.venv', 'env', '.git', '.idea', '__pycache__',
    'node_modules', '.vscode', 'build', 'dist', 'target',
    'logs', 'temp', 'tmp', 'assets', 'media'
}

# Расширения файлов, которые нужно собирать (код, конфиги, документация)
ALLOWED_EXTENSIONS = {
    '.py', '.js', '.ts', '.html', '.css', '.scss',
    '.json', '.yaml', '.yml', '.xml', '.txt', '.md',
    '.sql', '.sh', '.bat', '.env', '.dockerfile'
}

# Файлы, которые нужно игнорировать по имени
IGNORE_FILES = {
    OUTPUT_FILE, 'package-lock.json', 'yarn.lock', '.DS_Store'
}


def collect_code():
    project_root = os.getcwd()

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as outfile:
        outfile.write(f'Project Root: {project_root}\n')
        outfile.write('Generated by Project-to-Text-Merger\n')
        outfile.write('=' * 50 + "\n\n")

        # Записываем структуру проекта
        outfile.write('=== СТРУКТУРА ПРОЕКТА ===\n')
        for root, dirs, files in os.walk(project_root):
            # Фильтрация папок "на лету"
            dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

            level = root.replace(project_root, '').count(os.sep)
            indent = ' ' * 4 * level
            outfile.write(f'{indent}{os.path.basename(root)}/\n')
            subindent = ' ' * 4 * (level + 1)
            for f in files:
                if f not in IGNORE_FILES:
                    outfile.write(f"{subindent}{f}\n")

        outfile.write('\n\n=== FILE CONTENTS ===\n\n')

        # Проходим по файлам и записываем их содержимое
        for root, dirs, files in os.walk(project_root):
            dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

            for file in files:
                if file in IGNORE_FILES:
                    continue

                file_ext = os.path.splitext(file)[1]
                if file_ext in ALLOWED_EXTENSIONS or file == 'Dockerfile':
                    full_path = os.path.join(root, file)
                    rel_path = os.path.relpath(full_path, project_root)

                    # Пропускаем сам скрипт слияния
                    if os.path.basename(full_path) == os.path.basename(__file__):
                        continue

                    outfile.write(f'--- START OF FILE: {rel_path} ---\n')
                    try:
                        with open(full_path, 'r', encoding='utf-8') as infile:
                            outfile.write(infile.read())
                    except Exception as e:
                        outfile.write(f'Ошибка чтения файла: {e}')
                    outfile.write(f'\n--- END OF FILE: {rel_path} ---\n\n')

    print(f'✅ Готово! Весь код сохранен в файл: {OUTPUT_FILE}')
    print(f'📁 Размер файла: {os.path.getsize(OUTPUT_FILE) / 1024:.2f} KB')


if __name__ == '__main__':
    collect_code()
